# Generated by Django 4.2 on 2023-05-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('indicativo', models.CharField(max_length=10)),
                ('celular', models.CharField(max_length=20, unique=True)),
                ('documento', models.CharField(max_length=50)),
                ('numero_documento', models.CharField(max_length=50, unique=True)),
                ('fecha_expedicion', models.DateField()),
            ],
        ),
    ]
