# Generated by Django 4.2 on 2023-07-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetNow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='numero_cuenta',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='numero_tarjeta',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
