# Generated by Django 4.2 on 2023-04-19 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BetNow', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
