# Generated by Django 4.2 on 2023-07-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetNow', '0002_alter_banco_numero_cuenta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='numero_cuenta',
            field=models.CharField(max_length=20),
        ),
    ]
