# Generated by Django 4.2 on 2023-04-19 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BetNow', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='user',
        ),
    ]
