# Generated by Django 4.2 on 2023-04-23 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BetNow', '0006_perfil_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='is_active',
        ),
    ]
