# Generated by Django 4.2 on 2023-05-03 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('BetNow', '0009_user_delete_perfil'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Perfil',
        ),
    ]
